Aloxaf/fzf-tab

README.md, fzf-tab.zsh
Use a complete widget, so that the final result can be inserted by the builtin completion system, so that fzf-tab doesn't need to deal with various suffixes by itself.
Fix #6
Fix #7
Fix #9
=> Custom complete widget

fzf-tab.zsh
Example:
```text
gre█ 'query'
^ cursor
```
Press TAB and select `grep` from fzf. With `FZF_TAB_INSERT_SPACE=1` this used to result in the following completion:
```text
grep  'query'
^^ two spaces
```
With this PR:
```text
grep 'query'
^ one space
```
While at it, handle `FZF_TAB_INSERT_SPACE=0` as an explicit instruction to NOT insert space.
=> Don't insert space if RBUFFER already starts with space

fzf-tab.zsh
1. Use `: ${...}` instead of `[[ ${...} ]]` as this is the standard zsh idiom for discarding values of expansions performed for their side effects.
2. It's valid for `FZF_TAB_OPTS` to have empty value, so it shouldn't be replaced with the default.
3. Initialize `FZF_TAB_QUERY` the same way as other parameters for the sake of consistency.
=> Minor stylistic improvements in parameter declarations

fzf-tab.zsh
1. Make `i` local.
2. Stop setting `fzf_tab_default_completion` as it's no longer used.
3. Restore the original `^I` widget in `disable-fzf-tab`.
=> Minor cleanup

fzf-tab.zsh
There is a bug in Zsh that causes `local LC_ALL=C` to leak outside of its scope. As a result, in some environments fzf-tab changes user locale.
It's not important for candidates to be sorted in byte order, and it's also arguably worse than respecting the order prescribed by the user locale. So I'm removing it.
I think it was I who added this `local LC_ALL=C` in an earlier PR. Sorry about that.
=> bug fix: don't break user locale

README.md, fzf-tab.zsh
API explained [here](https://github.com/junegunn/fzf/wiki/Examples-(completion)), handy way of defining custom completions for particular commands.
Copied some functions from fzf [`completions.zsh`](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh) to allow not sourcing it.
=> Support FZF custom completion API

README.md, fzf-tab.zsh, test/.gitignore, test/comptest, test/fzftab.ztst, test/runtests.zsh, test/select, test/ztst.zsh
Fix #29 
Also provide many other features.
```zsh
zstyle ':completion:complete:*:options' sort false
zstyle ':fzf-tab:complete:_zlua:*' query-string input
zstyle ':completion:*:*:*:*:processes' command "ps -u $USER -o pid,user,comm,cmd -w -w"
zstyle ':fzf-tab:complete:kill:argument-rest' extra-opts '--preview=echo $(<{f})' --preview-window=down:3:wrap
local extract="
in=\${\${\"\$(<{f})\"%\$'\0'*}#*\$'\0'}
local -A ctxt=(\"\${(@ps:\2:)CTXT}\")
"
zstyle ':fzf-tab:complete:cd*' extra-opts --preview=$extract"exa -1 --color=always \${~ctxt[hpre]}\$in"
```
=> More configuration via zstyle

fzf-tab.zsh, test/fzftab.ztst
- Avoid running code with unknown options whenever possible. Put initialization code in an anonymous function with `emulate -L zsh`.
- Use only two sets of options for all code: (1) user-defined options only when it's strictly necessary; (2) the same set of "good" options everywhere else. This makes it much easier to reason about code.
- Remove `_ZSH_FZF_TAB_DISABLED`. It's inconsistently named, awkwardly used and is unnecessary.
- Don't rely on undocumented implementation details of zsh-autosuggestions.
=> minor and not-so-minor cleanup of the recent changes

fzf-tab.zsh
To reproduce:
git clone https://github.com/Aloxaf/fzf-tab.git
zsh -f
autoload -Uz compinit; compinit; source ~/fzf-tab/fzf-tab.zsh
ls /<TAB>
/
Expected:
❯ zsh -f
adam% autoload -Uz compinit; compinit; source ~/fzf-tab/fzf-tab.zsh
adam% ls /bin/
>
167/167
> bash
Note that current prompt shows `adam% ls /bin/`.
Actual:
❯ zsh -f
adam% autoload -Uz compinit; compinit; source ~/fzf-tab/fzf-tab.zsh
>
167/167
> bash
Note that current prompt is missing.
=> Bug fix: don't eat prompt line on continuous trigger

fzf-tab.zsh
Currently, when you invoke `fzf-tab-complete`, insert several completions with continous trigger and invoke `undo`, everything added by `fzf-tab-complete` gets removed. With this PR only the last completion gets removed.
To demonstrate:
zsh -f
autoload -Uz compinit; compinit; source ~/fzf-tab/fzf-tab.zsh
ls /<TAB>
usr/
bin<ENTER>
<CTRL-X><CTRL-U>
This PR should merge cleanly after #87.
=> Undo completions from contiguous trigger one by one

fzf-tab.zsh
This PR adds `DL_EXT=bundle` to the arguments of `./configure` when the OS is macOS (detected by `[[ ${OSTYPE} == darwin* ]]`), changing the extension of the compiled module from `.so` to `.bundle`, which `zmodload` would expect in macOS. This fixes #112
=> [Fix #112] Set DL_EXT=bundle if $OSTYPE is darwin*

fzf-tab.zsh
When `show-group` is set to brief, an error is raised by commands that don't provide a group. This happens in particular for commands using bash completion scripts like `aws`.
```sh
_fzf_tab_get_candidates:105: _fzf_tab_groups: assignment to invalid subscript range
```
This just adds a simple check for if the list is empty before accessing it
=> Check tab groups exist before hiding

fzf-tab.zsh, fzf-tmux-popup, fzf-tmux-popup.zsh
[![asciicast](https://asciinema.org/a/yiyBrosZ3OmgkNRJ3NLxObUe3.svg)](https://asciinema.org/a/yiyBrosZ3OmgkNRJ3NLxObUe3)
I love this. It won't push my prompt to the top of pane when the completion list is too long.
Close #128.
How to use (**need tmux 3.2!!**):
```zsh
FZF_TAB_COMMAND[1]=fzf-tmux-popup
zstyle ':fzf-tab:*' command $FZF_TAB_COMMAND
```
=> feat: add support for tmux popup

README.md, fzf-tab.zsh
This will close #79.
Example:
```zsh
zstyle ':fzf-tab:complete:*' extra-opts --preview=$fzf_tab_preview_init'
echo word: $word
echo description: $desc
echo group: $group
if (( $+ctxt[isfile] )); then
echo path: $realpath
fi
'
```
=> feat: more powerful preview

lib/-ftb-fzf, lib/ftb-tmux-popup
Many users have rm aliased to a different command or added flags such as `-I` or `-v`. Since these rm evocations aren't supposed to be verbose/visible, I'd find it best to force the use of the silent regular rm.
=> Use command rm when possible

fzf-tab.zsh
`FZF_TAB_HOME` will contain a wrong directory when instead of `fzf-tab.zsh` or `fzf-tab.plugin.zsh`, a symlink pointing to one of the two is sourced and the symlink lays in a different directory. In this case it will not contain the repository root but the directory in which the symlink is.
Errors also occur when the path of the repository contains spaces.
This fixes both of these issues by passing the path through `realpath` and quoting `$0`.
=> fix: FZF_TAB_HOME when a symlink is sourced or the path contains a space

fzf-tab.zsh
This PR adds checking `.bundle` as a module extension (for macOS) in the initialization code.
I forgot to add this check in the previous PR https://github.com/Aloxaf/fzf-tab/pull/121#issue-481954020 about module build in macOS.
=> fix: Check also .bundle as a module extension

fzf-tab.zsh, lib/-ftb-fzf
Allows a user to accept and run a suggestion in one keystroke.
https://asciinema.org/a/dMcynTzjKZRC0nZbvSo4gmIla
=> feat: add support of accept-line

fzf-tab.zsh
=> fix: print-query delete current words when no text is entered

fzf-tab.zsh, lib/-ftb-colorize
- Replace implicit `[[ $test ]]` with `[[ -n $test ]]`
- Doesn't fix the issue reported in #184, but it does at least make the issues more obvious
- ie. it would've saved me the time in changing all the logical conditions
- It's also recommended in the [zsh documentation](http://zsh.sourceforge.net/Doc/Release/Conditional-Expressions.html) to use the more explicit version
- > In other words, [[ $var ]] is the same as [[ -n $var ]]. It is recommended that the second, explicit, form be used where possible.
=> refactor: Add explicit non-zero length string tests

README.md
In case `ZSH_CUSTOM` isn't defined.
=> docs: fix oh-my-zsh installation path

lib/-ftb-fzf
I have changed the reload comand's `zsh` to `$(which zsh) -f`, as I have a lot of config in my zsh dotfiles which take seconds to load. `which zsh` is also better because `commands[zsh]` mistakenly returns a `zsh` directory in my path (I do have `setopt hash_executables_only`, but I think you do `emulate -L zsh` so it gets voided).
=> reload now runs zsh with -f

lib/ftb-tmux-popup
This fixes the tmux popup position when the status line is configured to be at the top of the window. It also correctly supports multi-line status.
To test this, here's an example of tmux.conf with 2 lines for the status at the top of the window:
```
set -g status 2
set -g status-position top
```
=> fix: position of tmux popup when status-position is 'top'

lib/ftb-tmux-popup
Might as well use Perl to calculate the max length too - it might be a micro-optimisation but it's one less `exec()` on every invocation of `ftb-tmux-popup`.
=> lib/ftb-tmux-popup: remove awk invocation from comp_length declaration

README.md
Apparently this was obvious to the developers of this package and to the thousands of people before me that installed this, but since I am an idiot I didn't realize that fzf MUST be installed in the system for fzf-tab to work.
Added a warning for the other idiots like me out there.
=> docs: added warning to install fzf

lib/ftb-tmux-popup
When the fzf's --info=inline or --info=hidden flags are passed the
height of the popup should be reduced to match the fzf height
=> fix: adjust the ftb-tmux-popup height with info style

fzf-tab.zsh
Fixes https://github.com/Aloxaf/fzf-tab/issues/221. This pull request introduces a new configuration flag `disabled-on`. It accepts the following values : 
| Value | Description |
|:---:|:--- |
| `any` | Disable fzf-tab for all matches. Fallback to the default completion selection menu. |
| `files` | Only disable fzf-tab if all of the matches are names of files. See flag `-f` in <https://zsh.sourceforge.io/Doc/Release/Completion-Widgets.html#Completion-Builtin-Commands>. |
| `none` | Enable fzf-tab for all matches. |
---
Configuration example for the use-case of https://github.com/Coqueiro
```zsh
zstyle ':fzf-tab:complete:cd:*' disabled-on any
```
Alternative configuration for the use-case of https://github.com/Coqueiro
```zsh
zstyle ':fzf-tab:*' disabled-on files
```
Configuration …
=> feat: toggle fzf-tab for a specific command

fzf-tab.zsh
`nproc` does not exist in macOS, therefore the number of CPU cores is not taken, nor additional cores are not utilized on macOS during the `build-fzf-tab-module()` call.
This PR solves this problem by using `sysctl` on macOS systems.
=> fix: CPU cores info on macOS

lib/-ftb-fzf, lib/ftb-tmux-popup
#
Add two new tags `fzf-min-height`, `popup-min-size`
| Tag            | Type   | Description                                |
| -------------- | ------ | ------------------------------------------ |
| fzf-min-height | int    | minimal height of fzf-tab widget           |
| popup-min-size | int[2] | minimal width and height of fzf-tmux-popup |
Setting a minimal size of fzf-tmux-popup window can prevent content from being
truncated by fzf preview window.
**default**
**zstyle ':fzf-tab:*' popup-min-size 60 8**
=> feat: add tags `fzf-min-height`, `popup-min-size`

lib/ftb-tmux-popup
Do you think this is a good change?
=> feat: swap tab and btab direction when tmux-popup shows above the cursor

fzf-tab.zsh
Rather than adding to `$FPATH` every time a new shell is created, check to see if it's already present. This means we don't end up with multiple instances of `${FZF_TAB_HOME}/lib` included in `$FPATH`.
```
$ echo $FPATH | tr ":" "\n"
[...]
${HOME}/fzf-tab/lib
$ zsh   # open a subshell
$ echo $FPATH | tr ":" "\n"
[...]
${HOME}/fzf-tab/lib
${HOME}/fzf-tab/lib
```
```
$ echo $FPATH | tr ":" "\n"
[...]
${HOME}/fzf-tab/lib
$ zsh   # open a subshell
$ echo $FPATH | tr ":" "\n"
[...]
${HOME}/fzf-tab/lib
```
=> fix: Only add to `$FPATH` once

fzf-tab.zsh
Adds -std=c99 compiler flag in build-fzf-tab-module() to fix the following error.
fzftab.c: In function ‘compile_patterns’:
fzftab.c:77:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
fzftab.c:77:5: note: use option -std=c99 or -std=gnu99 to compile your code
fzftab.c:93:14: error: redefinition of ‘i’
fzftab.c:77:14: note: previous definition of ‘i’ was here
fzftab.c:93:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
fzftab.c:104:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
fzftab.c: In function ‘colorize_from_name’:
fzftab.c:171:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
fzftab.c: In function ‘bin_fzf_tab_compcap_generate’:
fzftab.c:274:5: error: ‘for’ loop initial declarations are only …
=> fix: Adds -std=c99 compiler flag in build-fzf-tab-module()

lib/ftb-tmux-popup
Without this, I'm seeing "min / max / sum" already defined errors on
RHEL 8, the previous definition presumably from -ftb-fzf.
This seems independent of the Zsh version and I'm not really sure what
changed between RHEL 7 and RHEL 8 that triggers this.
=> tmux-popup: conditionally import math functions

fzf-tab.zsh, test/fzftab.ztst, test/select
This PR is another approch to let fzf-tab complete the common prefix.
It can handle some corner cases like https://github.com/Aloxaf/fzf-tab/pull/384#issuecomment-1957202220 and zsh-z.
**how to enable**
```zsh
zstyle ':completion:*' menu no
```
**known bugs**
~~It breaks multiple selections~~
**related issues/pr**
#8 #384
=> feat: prefix completion

fzf-tab.zsh, test/fzftab.ztst
this fix following bugs:
```zsh
_tst() {
compadd -J packages -X package openpgp-keys-gentoo-release -MERGING-pnpm-bin
}
compdef _tst tst
```
=> fix: remove -E from zparseopts

fzf-tab.zsh, test/fzftab.ztst
close #447
This behavior is different from compsys, but I think it is still worth fixing.
=> fix: prefix completion in quoted string

README.md
This PR adds an important note to the documentation, specifying that completions must be set up before running `compinit`.
I spent several hours troubleshooting a problem where I thought `fzf-tab` was not working correctly. After a while, I realized that the issue was due to setting the `fpath` AFTER `compinit`. 
So in order to help users that manually install zsh plugins not to have the same issue, I added that note.
=> docs: add info about completions

lib/-ftb-fzf, lib/-ftb-generate-complist
This PR is based on the thread of discussion in https://github.com/Aloxaf/fzf-tab/issues/477. The goal of this PR is to make it so that in order to theme fzf-tab with the same colors as your normal fzf theme, users can use just the following settings in their .zshrc:
```zsh
zstyle ':fzf-tab:*' use-fzf-default-opts yes
source ~/code/fzf-tab/fzf-tab.zsh
```
As fzf-tab works today, the required settings are:
```zsh
zstyle ':fzf-tab:*' use-fzf-default-opts yes
#
#
zstyle ':fzf-tab:*' fzf-flags --color=hl:myThemeColor
#
#
zstyle ':fzf-tab:*' default-color ""
source ~/code/fzf-tab/fzf-tab.plugin.zsh
```
As a new user of fzf-tab, I am extremely grateful for this project. It works very well and between the fzf knowledge, shell knowledge, and c knowledge required to make it work so quickly, I am …
=> Remove text-coloring that interferes with fzf theming

fzf-tab.zsh
Subshells cause zsh to try and render their prompt. For reasons I do not entirely understand, zsh does not expand `$PROMPT` correctly in this case when PROMPT_SUBST is set.
Fortunately, using a brace group instead of a subshell is simple and has the same meaning.
Fixes #513
=> Avoid spawning a subshell in `-ftb-compadd`

lib/-ftb-generate-header
This commit adds a new `show-group` style value: `quiet` [^naming] .
Specifying this option prevents any group headers from displaying in the completion list, while still providing the `${group}` value(s) to FZF preview/shell commands. This is an alternative to `show-group none` where no headers are shown, but all `${group}` values are replaced by `__hide__`.
[^naming]: I initially used `show-group hide` before I remembered `__hide__` is in use with `show-group none`.
----
Consider the following zstyles:
<details><summary>Details</summary>
<p>
```shell
zstyle ':fzf-tab:*:file:*' fzf-flags --height=~80% --style=full --query='!^.' --header-label=' File Type '
zstyle ':fzf-tab:*:file:*' fzf-bindings 'focus:transform-header(
{_FTB_INIT_} {
file -LIb ${realpath} || echo "No file selected"; …
```
=> Support retaining `${group}` values while not displaying group headers
