- fzf-tab.zsh
Speed things up a little:
- Avoid forks.
- Avoid loops.
The standard way to return values from zsh functions (be it scalars, arrays or associative arrays) is through named parameters. This works thanks to dynamic scope.
```zsh
function f() { typeset -g REPLY=$1$1$1 }
function g() {
local REPLY
f foo
echo -E - $REPLY
}
REPLY=bar
g                 # prints "foofoofoo"
echo -E - $REPLY  # prints "bar"
```
There is one non-trivial combination of expansions in this PR that is used to find common prefix. I added several comments around it to make it less impenetrable. Hopefully they make the code understandable.
> Minor performance improvements

- fzf-tab.zsh
There are two parts to this commit:
1. Ensure that `fzf-tab.zsh` is always parsed the same way regardless of options and global aliases. For example, if `alias -g input='<$TTY'` is defined before `fzf-tab.zsh` is sourced, it results in an error without this commit. The solution is to unset `aliases` at the top of `fzf-tab.zsh` and set it back at the bottom. Until this option is unset, everything has to be quoted to prevent alias expansion (hence `'builtin' 'local' '-a' '_fzf_tab_opts'`). Similar measures are taken w.r.t. `sh_glob` and `brace_expand` as these options also affect how functions are parsed.
2. Ensure that functions execute with a known set of options. For example, the code relies in several places on array subscripts being 1-based. If the user sets `ksh_arrays`, the code will …
> Survive any combination of zsh options and global aliases

- fzf-tab.zsh
> Skip fzf if all candidates are for the same word

- README.md
- fzf-tab.zsh
Fix #11 
Select with `Ctrl+Space`
> Allow selecting multiple items

- README.md
- fzf-tab.zsh
This PR gives different colors to different groups, and keep the group order.
Fix #19 
TODO:
> Support grouping

- fzf-tab.zsh
1. Use `function foo() {..}` syntax for defining functions instead of `functions[foo]='...'`.
2. Use unique and ugly names for variables that must be reachable across scopes outside of fzf-tab's control.
3. Don't use `&&` for control flow when executing code with user options. It breaks when `err_return` is set.
4. Use `always` to restore `_main_complete` to make breakage less likely.
> minor fixes

- README.md
- fzf-tab.zsh
> Continuous completion

- README.md
- fzf-tab.zsh
> fzf-tab-toggle

- fzf-tab.zsh
- make sure all sublists succeed when `err_return` might be set
- don't assume that `${(q)...}` correctly escapes regex (it doesn't)
- don't use `${x[1]}` when `ksh_arrays` might be set (it makes arrays 0-based)
- don't hard-code `_fzf_complete_`
- don't eval the first token in `$LBUFFER`
- don't export `prefix`
@doubleloop Could you double-check that this change doesn't break stuff?
> fix a few bugs in _fzf_tab_try_custom_completion

- fzf-tab.zsh
- test/fzftab.ztst
> Call _fzf_tab_complete directly in _main_complete

- fzf-tab.zsh
`sort -t '\0'` doesn't work on busybox:
```text
❯ sort -t '\0'
sort: bad -t parameter
❯ echo ${commands[sort]:A}
/bin/busybox
```
I've replaced `sort -t '\0' -k2` with this sequence:
1. move the first field to the end
2. sort
3. move the last field to the front
I've made a couple additional loosely related changes that seemed to make sense. Please double-check that my reasoning is correct.
1. I've removed number sorting: `-n` in `sort` and `(n)` in zsh. This code is sorting either completion candidates themselves or their group names. Neither are numbers. I don't think it makes much of a difference either way, so if there is even a slight reason to use number sorting, I won't mind it in the slightest.
2. The original sort had `-u` which doesn't seem necessary. I've removed it.
> replace `sort -t '\0'` with a portable alternative

- README.md
- README_CN.md
- fzf-tab.zsh
- test/fzftab.ztst
- test/select
Now we can use `alt-enter` to use the user input as the final result
Close #102
> feat: add support of print-query

- README.md
- README_CN.md
> docs: fix typos

- README.md
> Added Prezto install how-to to README.md

- README.md
Just some minor edits to the README.
> Improve language

- fzf-tab.zsh
- lib/-ftb-fzf
> fix: failed to read /dev/tty

- lib/-ftb-fzf
This seems to solve https://github.com/Aloxaf/fzf-tab/issues/206 .
> now empties /dev/tty before passing it to fzf

- lib/-ftb-fzf
> fix: realpath

- fzf-tab.zsh
> fix: continuous completion

- lib/-ftb-fzf
> fix: windows path

- lib/-ftb-fzf
Squashed version of pull request #299
> feat: add words array to environment

- lib/ftb-tmux-popup
> fix(ftb-tmux-popup): default shell

- fzf-tab.zsh
> fix: completion is missing for history command

- fzf-tab.zsh
> fix: nounset

- fzf-tab.zsh
> fix: solving msys2 regressions
